services:
  caddy:
    image: caddy:2-alpine
    container_name: nokeycloud-proxy
    ports:
      - "8780:80"
      - "8743:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    container_name: nokeycloud-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nokeycloud_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nokeycloud_password}
      POSTGRES_DB: ${POSTGRES_DB:-nokeycloud_db}
    volumes:
      - ./data/db_data:/var/lib/postgresql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nokeycloud-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-nokeycloud_redis_password}
    volumes:
      - ./data/redis_data:/data
    restart: unless-stopped
    
  setup-permissions:
    image: alpine:latest
    container_name: nokeycloud-setup
    restart: "no"
    volumes:
      - ./data:/host_data
    command: sh -c "mkdir -p /host_data/upload && chown -R 1654:1654 /host_data/upload"

  backend:
    build:
      context: .
      dockerfile: src/backend/noKeyCloud.api/Dockerfile
      network: host
    container_name: nokeycloud-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=postgres://${POSTGRES_USER:-nokeycloud_user}:${POSTGRES_PASSWORD:-nokeycloud_password}@db:5432/${POSTGRES_DB:-nokeycloud_db}
      - REDIS_HOST=redis:6379,password=${REDIS_PASSWORD:-nokeycloud_redis_password}
      - JwtSettings__SecretKey=${JWT_SECRET:-zwotTvJmQiQvvipwDfFZ0+r7Go3iwBbvaGlqSb0G9JhxhhCYi9K0ZIAI+tJY2BfdqdG7e+ZcAupA+MCC+3x4RHQFQt2Ra8a5JN19YYQkwbpgBKp6+Hfrlvpl8hGR/VLU1s16Laaoe3CL5IbpyE2JadjRubw4Xaegx2qpeSQ0THE=}
      - FRONTEND_URL=https://${DOMAIN_NAME:-localhost}:8743
      - BASE_UPLOAD_STORAGE_PATH=${BASE_UPLOAD_STORAGE_PATH:-/uploads}
    volumes:
      - ./data/app_data:/data
      - ./data/app_config:/config
      - ./data/upload:/uploads
    depends_on:
      setup-permissions:
        condition: service_completed_successfully
      db:
        condition: service_started
      redis:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: src/frontend/web
      dockerfile: Dockerfile
      network: host
      args:
        - VITE_BACKEND_URL=https://${DOMAIN_NAME:-localhost}:8743
    container_name: nokeycloud-frontend
    depends_on:
      - backend
    restart: unless-stopped